### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by felek000** [symfony-cmf/cmf-sandbox#272]
Hello, I download and install sandbox and all works good except two thinks. 
When I edit post in fronted and I open media explorer, and get error:
 "Unable to open "default folder".Folder not found."
I try to create media folder in many places inside of web directory no results. How can I change or find name of that folder ? From backed I can upload images and directory structure is showing still on front I cant upload it.
Also how can I enable ckeditor inside on backend ? On demo there is no rich editor when eddit or add post.
Many thanks for help.

**Comment by Yaghiyah** [comment]
can someone please confirm how this problem was solved ?? I'm dealing with same issue, and it looks like no solution was provided to guide future problems like this.

**Comment by dbu** [comment]
hm, the sandbox.cmf.symfony.com installation has the same issue. so it indeed looks like this needs to be fixed. i don't know if its in the MediaBundle PHPCR adapter for elfinder, or just a configuration mistake.

**Comment by Yaghiyah** [comment]
Thanks David, do have a look and let us know. Appreciate it.

**Comment by dbu** [comment]
this is the same issue as #302, right?

**Comment by Yaghiyah** [comment]
correct.

**Comment by morwalz** [comment]
HI anyone found any answer for this problem ? i am facing same problem
