### ISSUE TITLE
cmf - NotFoundHttpException: No route found for "GET /" issue

### ISSUE THREAD

**Issue by dulguuntur** [symfony-cmf/cmf-sandbox#285]
I just installed symfony-cmf successfully. but when i access to localhost:8000, this error appears. i dont know how to fix this error. help me pls guys :)
[2/2] NotFoundHttpException: No route found for "GET /"   +
[1/2] ResourceNotFoundException: None of the routers in the chain matched this request
GET / HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,ru;q=0.6
Connection: keep-alive
Cookie: PHPSESSID=ldq80rd80l009kuu5edaelf435; sonata_page_is_editor=1
Host: localhost:8000
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
X-Php-Ob-Level: 1

ERROR - Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/dulguuntur/Public/tdb_bank/app/cache/dev/classes.php line 2017

**Comment by dbu** [comment]
did you follow all steps of the setup in the readme, and get no errors during the import fixtures step? https://github.com/symfony-cmf/cmf-sandbox#import-the-fixtures

**Comment by dulguuntur** [comment]
wow its working now .. ty :)

**Comment by dbu** [comment]
you are welcome. don't hesitate to open further issues if you run into problems, or use the mailinglist https://groups.google.com/forum/#!forum/symfony-cmf-users or #symfony-cmf on irc.freenode.net
