### ISSUE TITLE
Add stringblock to sandbox

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/cmf-sandbox#289]
Currently the "Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\StringBlock" is not enabled in the config. Not sure if this is intentional, but I find that block to be really helpful and since this sandbox seem to show most, if not all options, it would be cool to get people familiar with the stringblock.

**Comment by dbu** [comment]
i think the "reason" is we added the StringBlock after doing block demos in the sandbox. would love to see an example of it in the sandbox. maybe make the "Powered by..." in the footer a string block that is editable? attach it to homepage and reference it with absolute path. (once ResourcesBundle is released, we can use that to make it more elegant).

do you want to do a pull request for that @ConneXNL ?
