### ISSUE TITLE
Manage Languages

### ISSUE THREAD

**Issue by ferrassi** [symfony-cmf/cmf-sandbox#290]
Hi,
Symfony2 CMF Sandbox comes in 3 language packs : English ,deutsch and french,
How to add another language ?
Can anyone help me.

**Comment by dbu** [comment]
the cmf just builds on top of symfony itself. read the symfony book section on [translation](http://symfony.com/doc/current/book/translation.html) to get familiar with how the system texts are translated. you will need to add translation files for missing languages. some of the cmf bundles come with many more translations that where contributed.
if you do translate some bundle system messages, please do a pull request to add the translation to the corresponding repository so it will be further updated.

for doctrine phpcr-odm, make sure to add your new locale to the `locales` parameter and you should be all good to go and add content in your new locale and have the locale bundle provide a locale switcher with that new locale.
