### ISSUE TITLE
elfinder not working ?

### ISSUE THREAD

**Issue by revollat** [symfony-cmf/cmf-sandbox#295]
In the demo site elfinder doesn't seems to work.

Error message : Invalid backend configuration.
Readable volumes not available.

![image](https://cloud.githubusercontent.com/assets/3305494/9301408/7ae57e40-44ce-11e5-8dad-fe804cb190f7.png)

Any solution ?

**Comment by revollat** [comment]
I just upgrade to version 5 of elfinder bundle and now it seems to work ...

**Comment by lsmith77** [comment]
ok great .. so we can close this ticket or do you think there is something that needs to be added to the docs?

**Comment by dbu** [comment]
if the default install of the sandbox does not work, we should update
the elfinder bundle version in the sandbox.

did you just `composer install` or anything else?
does the unmodified installation at cmf.liip.ch work or not?

**Comment by revollat** [comment]
The screenshot is taken from cmf.liip.ch, so it doesn't work on the demo site :)

I reproduced the pb in local with the github source.

**Comment by lsmith77** [comment]
ah. can you submit a PR to update the elfinder in this repo?

**Comment by revollat** [comment]
OK
