### ISSUE TITLE
Failed to download zendframework/zend-servicemanager

### ISSUE THREAD

**Issue by MichalMajer** [symfony-cmf/cmf-sandbox#303]
Hi,

I've been trying to download and run the Symfony CMF Sandbox, but I'm faced with this error when running "composer install":

Failed to download zendframework/zend-servicemanager from dist: The "https://api.github.com/repos/zendframework/Component_ZendServiceManager/zipball/559403e4fd10db2516641f20f129a568d7e6a993" file could not be downloaded (HTTP/1.1 404 Not Found)

And then:

[RuntimeException]                                                                                      
  Failed to clone git@github.com:zendframework/Component_ZendServiceManager.git via git, https, ssh prot  
  ocols, aborting.                                                                                        
  - git://github.com/zendframework/Component_ZendServiceManager.git                                       
    Cloning into '/Users/Mike/Sites/bk_tests/symfony-play/symfony_cmf/vendor/zendframework/zend-servicem  
  anager/Zend/ServiceManager'...                                                                          
    fatal: remote error:                                                                                  
      Repository not found.                                                                               
  - https://github.com/zendframework/Component_ZendServiceManager.git                                     
    Cloning into '/Users/Mike/Sites/bk_tests/symfony-play/symfony_cmf/vendor/zendframework/zend-servicem  
  anager/Zend/ServiceManager'...                                                                          
    remote: Repository not found.                                                                         
    fatal: repository 'https://github.com/zendframework/Component_ZendServiceManager.git/' not found      
  - git@github.com:zendframework/Component_ZendServiceManager.git                                         
    Cloning into '/Users/Mike/Sites/bk_tests/symfony-play/symfony_cmf/vendor/zendframework/zend-servicem  
  anager/Zend/ServiceManager'...                                                                          
    Permission denied (publickey).                                                                        
    fatal: Could not read from remote repository.                                                         
                                                                                                          
    Please make sure you have the correct access rights                                                   
    and the repository exists.

**Comment by dbu** [comment]
what version of the sandbox are you using? latest master or a stable tag?

**Comment by MichalMajer** [comment]
I took the version from the official documentation on http://symfony.com/doc/current/cmf/cookbook/editions/cmf_sandbox.html

composer create-project --no-install symfony-cmf/sandbox <path-to-install> '~1.2'

**Comment by WouterJ** [comment]
Turns out we didn't release a new 1.2 version after Zend framework decided to change all its package URLs. I've now created [1.2.1](https://github.com/symfony-cmf/cmf-sandbox/releases/tag/1.2.1) to fix this.

This won't help you, as you can't update created projects. However, executing `composer update` will solve the problem for you. Further users will get 1.2.1, with the fix.

Thanks for reporting this bug!
