### ISSUE TITLE
Add a way to add content/seometadata for an existing symfony route/controller

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/cmf-sandbox#309]
I am not sure if this is the best way to add content/seometadata for an existing symfony route/controller but the following is working well for me:

https://github.com/ConneXNL/cmf-sandbox/blob/master/src/AppBundle/Twig/CmfExtraExtension.php

If this is the correct way to achieve this goal, is this an option to add to any of the Cmf Bundles? Or maybe add an example of this usage in the cmf-sandbox?

This basically makes it very easy to add CMF functionality to existing bundle functionality by only coupling it via a single twig function.

**Comment by lsmith77** [comment]
as I replied in the IRC channel .. we would recommend using http://symfony.com/doc/current/cmf/bundles/core/templating.html

the overhead of combining multiple twig function calls is very small.

generally I would however advise to keep the logic inside a template as small as possible ..
