### ISSUE TITLE
Edit body in static content - 500 Internal Server Error

### ISSUE THREAD

**Issue by damonsson** [symfony-cmf/cmf-sandbox#316]
If I try click update, I have error.
Locally i enable show errors and have exception: `LogicException: Can not determine the prefix. Either this is a new, unpersisted document or the listener that calls setPrefix is not set up correctly.`

http://sandbox.cmf.symfony.com/en/admin/app/demoseocontent/cms/content/company/edit

**Comment by WouterJ** [comment]
Thank you for reporting this issue. 

It seems like a bug with the FrontendLinkExtension of the CmfRoutingBundle. For some reason, the ContentAwareGenerator generates a `Route` object with all empty fields. (/cc @dbu could be a CmfRouting bug as well).

To improve demo user experience for the moment, I've disabled this extension and everything works (at least, locally).

**Comment by WouterJ** [comment]
It's still not working. Now failing iwth form errors, about route fields being blank.

@dbu it seems like something is completely wrong with the route referrer extension. Sonata believes there are 3 empty routes attached to the static content, while there are 0 routes attached.

**Comment by WouterJ** [comment]
This might even be an issue with Doctrine PHPCR-ODM. As the content has routes (3, one for each language), but the `ReferrersCollection` returned by `$content->getRoutes()` contains 3 empty routes (only the path property is set, no name, content document, etc.). I guess this has something to do with the prefetch stuff that has been added to the ReferrersCollection in 1.3.

**Comment by damonsson** [comment]
Temporary if you need edit static page, you must first remove any routes related to this page. Edit page, and **after**, recreate deleted routes.

Any progress with fix it? I will try, but is too many dependentions between bundles to analyze and debug for me.

**Comment by WouterJ** [comment]
Finally found the issue, a wrong class name somewhere in the code: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/360
