### ISSUE TITLE
Admin dashboard link

### ISSUE THREAD

**Issue by manact** [symfony-cmf/cmf-sandbox#321]
Have installed 3 times the sandbox but no way to get inside the admin.
Debian 8.2 - Apache 2.4 - php 5.6.14 
Composer install with all agreed.
I still have an http credential with suggested admin/admin but can't go further.

newbee inside?

**Comment by WouterJ** [comment]
I'm afraid we need a bit more details in order to help you.

 * What do you mean with "can't go further"? Do you see an error page, do you get the prompt again, are you redirected?
 * What happends if you go to `/admin/dashboard` directly? (also after logging in?)
 * Does the toolbar show you as authenticated (and admin user, or anon.)?
 * Can you find anything security related in `app/logs/dev.log`?

**Comment by dbu** [comment]
did you follow all steps in the setup instructions in the readme?
particularly loading the fixtures?
https://github.com/symfony-cmf/cmf-sandbox#import-the-fixtures

the users for the sandbox are defined in the parameters file:
https://github.com/symfony-cmf/cmf-sandbox/blob/master/app/config/parameters.yml.dist#L26
(which is not a practice we would recommend for any real projects, its
just for the demo)

**Comment by manact** [comment]
@WouterJ 
As I started here, I continue here but thank you to point me the freenode. Next time I'll use it.

- The toolbar shows anon. (/app_dev.php)
- Yes prompt again again. White page. (/app_dev.php/fr/admin/dashboard)
The log shows a security.debug :
security.DEBUG: Access denied, the user is not fully authenticated; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at /home/sites/mysite/www/htdocs/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:70)"}

This is followed by : security.DEBUG: Calling Authentication entry point.

@dbu 
- Yes fixtures are loaded correctly
- The parameters.yml show the two type of users and their respective password.

**Comment by manact** [comment]
Hello! Still blocked, here!
I have no php/apache logs errors except 401

**Comment by dbu** [comment]
the online demo works: http://sandbox.cmf.symfony.com
so i suspect its something with your setup. you should get a popup window for the basic authentication. if things fail after that, it could be something with the enabled php extensions or maybe the session store that can not be written to.

> Hello! Still blocked, here!

sorry about that. if i can help i am glad to. but this is open source and i am helping you in my free time, there is no urgent support contract (and even those usually do not guarantee responses within the hour...)

**Comment by manact** [comment]
Yes, I hear you very well and, with much respect, really appreciate your help.
With no apparent errors, I really don't know where to search and how I could collaborate.
I will change my setup and search again. Thank you.

**Comment by manact** [comment]
@dbu @WouterJ 
Like dbu said, all was in configuration.
In particular, multiple php versions with apache on a single server with fastcgi and pools.
For my virtualhost, I was using a proxy redirect for the php calls and that wasn't the nice way to do it.
Everything is working now (socket based) and will provide/discuss my setup if needed.

Thanks,
Michel

**Comment by dbu** [comment]
:+1:
