### ISSUE TITLE
Multilingual "Team", "More", "The Company"

### ISSUE THREAD

**Issue by maity-kgz** [symfony-cmf/cmf-sandbox#323]
Could some one explain why this "Team", "More", "The Company" etc pages can not be translated to German and France in admin panel whilst "Home" page can ?
I see that HOME page loaded first time from fixtures in 3 lang whilst others not. But all of them are DemoSeoContent documents which is translatable.
Same problem if I create new page, can not add other languages.

**Comment by dbu** [comment]
@WouterJ would you happen to know this? it looks like switching the language of the content (with the little flags) does not lead to the content being saved in that language, but instead overwriting the loaded language: http://sandbox.cmf.symfony.com/en/admin/app/demoseocontent/cms/content/team/edit?tl=fr . when a language is not available, phpcr-odm falls back to an other language and remembers what language that was, saving by default updates the loaded language - unless we explicitly set the field that is mapped to the locale, or use persistTranslation with an explicit locale.

**Comment by WouterJ** [comment]
@dbu I think the SonataTranslationBundle probably doesn't handle the case of adding new translations correctly for PHPCR. Can you maybe take a look at https://github.com/sonata-project/SonataTranslationBundle/blob/master/Admin/Extension/Phpcr/TranslatableAdminExtension.php ?

**Comment by dbu** [comment]
hm, there is even a comment in there by @nicolas-bastien pinging my name
https://github.com/sonata-project/SonataTranslationBundle/blob/master/Admin/Extension/Phpcr/TranslatableAdminExtension.php#L43

indeed we need to set the locale field or bind the translation before
saving - maybe that code is when loading the document, not sure. i am
travelling now and wont have time to look into this in the next 3 weeks,
sorry.

**Comment by maity-kgz** [comment]
@dbu this is very critical issue. Seems like that its trailing from the beginning and Sandbox never were multilingual actually.
Could you point me more specifically where to look at to solve this at least locally for my current project on Symfony CMF. Thank you.

**Comment by dbu** [comment]
yeah it looks like /creating/ new translations is broken. i am travelling
without my computer so i cant go deep into this now. but i try to explain
and hope you can find the issue: when loading the document we need to
findTranslation because by default phpcr-odm will use the request language,
but we have this content language. when saving we need to bindTranslation
so that the translation in a new language is created. i am not sure at what
point the alterObject is executed, check if there is a post load and a pre
update step of some sorts. the alternative to bindTranslation is setting
the field mapped to '@Locale' to the new content language

**Comment by WouterJ** [comment]
Please note that we just switched to SonataTranslationBundle, I believe the TranslatableExtension we used before did work correctly.

`alterObject` is executed when loading it. There are quite some methods that are executed before update/persist: https://github.com/sonata-project/SonataAdminBundle/blob/956221be72f0c3a2ce6bc997a397120cad5659d3/Admin/AdminExtensionInterface.php#L153-L183

In this method, we have to execute the bindTranslation method that is shown here: https://github.com/sonata-project/SonataTranslationBundle/blob/master/Admin/Extension/Phpcr/TranslatableAdminExtension.php#L43

**Comment by maity-kgz** [comment]
Traced function calls from `alterObject` and found next:
`alterObject` calls `findTranslation() `function and pass desired `locale`. --- here is OK, locale = FR
`findTranslation` calls `doLoadTranslation() `and also pass desired `locale` --- here is OK, locale = FR
but in `doLoadTranslation() `locale is always NULL. That is why document fallback to current locale which is EN in most cases.

Question is why `locale` is always NULL in `doLoadTranslation` while `findTranslation` pass non NULL `locale` ??? Between this calls something happened and `locale` turned to NULL.

**Comment by WouterJ** [comment]
@maity-kgz by applying this patch, I am able to create new translations: https://github.com/sonata-project/SonataTranslationBundle/pull/78
