### ISSUE TITLE
block template ""

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/cmf-sandbox#325]
i tried to upgrade all cmf things, but get

     Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "" 

@WouterJ i think i saw some comment from you about sonata version 2.3 and a BC break with which method is called to set the options, but i can't find it anymore. thought it was on the SonataTranslationBundle somewhere but had no luck finding it.

i have some time to wrap up things this week, and getting the multilang sonata to work correctly is high on my list. glad if you can give me some pointers.

**Comment by WouterJ** [comment]
I don't exactly what caused the error, but the problem is with the block settings. The template is set as default value of a block setting. For some reason, the value of the template setting is set to an empty string, causing this error.

**Comment by dbu** [comment]
ah, found it: https://github.com/sonata-project/SonataTranslationBundle/issues/55#issuecomment-174464774
