### ISSUE TITLE
Iconfont broken on sandbox install

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/cmf-sandbox#331]
the icons on http://sandbox.cmf.symfony.com/en/admin/dashboard do not seem to work. we just see placeholders.

**Comment by WouterJ** [comment]
Hmm, this applies to some browsers and OSes only (as some fonts are available). The icon font is loaded by Sonata and available in `bundles/sonatacore`. I'll check why some of the icon font files can't be loaded...

**Comment by WouterJ** [comment]
Little misconfiguration of platform.sh resulting in the font files to be routed through Symfony. I've now whitelisted the `/bundles/` directory to be available without passing through Symfony: https://github.com/symfony-cmf/cmf-sandbox/commit/75901e675f2b1abfaec7a642052653e2e823e799

Things seem to work now, feel free to reopen when things are still wrong.

**Comment by dbu** [comment]
yep, fixed. thanks a lot!
