### ISSUE TITLE
Fatal error on updating static content (Symfony 3 compat)

### ISSUE THREAD

**Issue by maity-kgz** [symfony-cmf/cmf-sandbox#336]
@dbu @wouterj 
Fatal error: Call to undefined method Symfony\Component\Validator\Context\ExecutionContext::addViolationAt() in /app/vendor/doctrine/phpcr-bundle/Validator/Constraints/ValidPhpcrOdmValidator.php on line 64

Occurs when you try edit title or body and hit update button  of existing static content.
Tested on online sandbox.

**Comment by maity-kgz** [comment]
taken from the the UPGRADE FROM 2.x to 3.0 log...

The method `addViolationAt()` was removed. You should use `buildViolation()`
instead.

Before:

$context->addViolationAt('property', 'The value {{ value }} is invalid.', array(
    '{{ value }}' => $invalidValue,
));

After:

$context->buildViolation('The value {{ value }} is invalid.')
    ->atPath('property')
    ->setParameter('{{ value }}', $invalidValue)
    ->addViolation();
));

**Comment by wouterj** [comment]
This is fixed, but not in the current set of dependencies (as there is a problem) (see also #335).

**Comment by wouterj** [comment]
The new dependency set is now included and this issue is fixed. Thanks for your report!
