### ISSUE TITLE
Issue in redirection flow on "http://sandbox.cmf.symfony.com/en"

### ISSUE THREAD

**Issue by nexuslinkservices** [symfony-cmf/cmf-sandbox#338]
Being curious I visited the site to experience the live demo of CMF-sandbox.
When I clicked "Admin Dashboard", one form prompted asking for the Credential required to access the admin panel. 
As I don't have the admin account I clicked on the "Cancel" button. I get redirected to blank page addressing the "http://sandbox.cmf.symfony.com/en/admin/dashboard"

**Comment by wouterj** [comment]
This is expected behaviour (and not something the CMF can control, it's a Symfony framework feature or even more an HTTP feature).

Btw, the admin account is admin/admin (username/password). I'll look how we can add this information in the login prompt, so people can login directly.

**Comment by dbu** [comment]
the basic auth prompt does tell the password: "A username and password are being requested by http://sandbox.cmf.symfony.com. The site says: "Secured Demo Area (username: admin, password: admin)""
