### ISSUE TITLE
Attempted to load class "SimpleChoiceList" from namespace "Symfony\Component\Form\Extension\Core\ChoiceList".

### ISSUE THREAD

**Issue by samanmohamadi** [symfony-cmf/cmf-sandbox#346]
symfony-cmf/symfony-cmf#234 
it seems to be BC related to symfony 3

**Comment by dbu** [comment]
do you see this exception in the sandbox? can you link to the page on http://sandbox.cmf.symfony.com/en that would show the admin where it happens?

**Comment by samanmohamadi** [comment]
@dbu  Thanks for your response.
problem solved
