### ISSUE TITLE
Link to configuration file is boken

### ISSUE THREAD

**Issue by Bolland** [symfony-cmf/cmf-sandbox#349]
The link to the configuration file on the cmf sandbox is broken: http://sandbox.cmf.symfony.com/news/2016-09-19/routingautobundle-generates-routes

It links to https://github.com/symfony-cmf/cmf-sandbox/tree/1.2/src/AppBundle/Resources/config/cmf_routing_auto.yml which doesn't exist (any more).

**Comment by dbu** [comment]
fixed in master, thanks for notifying us
