### ISSUE TITLE
PHPCRException: The Id is immutable

### ISSUE THREAD

**Issue by samanmohamadi** [symfony-cmf/cmf-sandbox#350]
Trying to change content node name getting this error:
**PHPCRException: The Id is immutable (/cms/content/f/seoMetadata !== /cms/content/f2/seoMetadata). Please use DocumentManager::move to move the document: Symfony\Cmf\Bundle\SeoBundle\Doctrine\Phpcr\SeoMetadata@00000000610b7ca50000000049e6660c (/cms/content/f2/seoMetadata)**

**Comment by dbu** [comment]
the exception is correct and telling you what to do: don't change the node name but call DocumentManager move with your document.

**Comment by samanmohamadi** [comment]
I am using sonata admin interface, you mean it isn't possible to change node name through admin panel?
