### ISSUE TITLE
CMF Sandbox host: "No space left on device"

### ISSUE THREAD

**Issue by jlamur** [symfony-cmf/cmf-sandbox#368]
The [Symfony CMF Sandbox](http://sandbox.cmf.symfony.com/en) shouts the following error on every page:

> Warning: SessionHandler::write(): write failed: No space left on device (28) in /app/var/cache/prod/classes.php on line 370
> Warning: session_write_close(): Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/app/var/cache/prod/sessions) in /app/var/cache/prod/classes.php on line 151

This prevents from using sessions, so we can't login to the Admin Dashboard.

**Comment by dbu** [comment]
thanks, we have reset the sandbox and it seems fine again.
