### ISSUE TITLE
Some missing translations

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/cmf-sandbox#381]
Before releasing we should have a look onto the translations keys. i.e. `form.label_key` and `from.label_value` is missing in SeoExtension.

**Comment by dbu** [comment]
would that be an issue of the sonata integration package then?

**Comment by ElectricMaxxx** [comment]
ah, yes right :-) those translations come from that namespace

**Comment by ElectricMaxxx** [comment]
moved to https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/issues/121
