### ISSUE TITLE
Live Demo not working

### ISSUE THREAD

**Issue by brud** [symfony-cmf/cmf-sandbox#390]
http://sandbox.cmf.symfony.com/en shows an error:

> Warning: mkdir(): No space left on device in /app/vendor/symfony-cmf/seo-bundle/src/Cache/FileCache.php on line 43
> Oops! An Error Occurred
> 
> The server returned a "500 Internal Server Error".
> 
> The admin tool currently allows full access to the entire content tree. As a result its possible to break
> the entire routing configuration. In many cases when you see an error on this site, its caused by
> someone having done exactly that. You can reload the entire content to the original state by calling
> reload-fixtures.php

When I try reload fixtures by  [link](http://sandbox.cmf.symfony.com/reload-fixtures.php), I get this error:

> Running: /app/web/../bin/console cache:clear -e=prod
> Output:
> 
> Warning: mkdir(): No space left on device in /app/vendor/symfony-cmf/seo-bundle/src/Cache/FileCache.php on line 43
> 
>  // Clearing the cache for the prod environment with debug
>  // false
> 
>  [WARNING] Calling cache:clear without the --no-warmup option is deprecated
>            since version 3.3. Cache warmup should be done with the cache:warmup
>            command instead.

> Running: /app/web/../bin/console -v doctrine:phpcr:fixtures:load -e=prod
> Output:
> 
> Warning: mkdir(): No space left on device in /app/vendor/symfony-cmf/seo-bundle/src/Cache/FileCache.php on line 43
  > purging database
  > Executing initializer: CmfRoutingBundle
  > Executing initializer: CmfMenuBundle
  > Executing initializer: CmfContentBundle
  > Executing initializer: CmfBlockBundle
  > Executing initializer: CmfRoutingAutoBundle
  > loading [5] AppBundle\DataFixtures\PHPCR\LoadStaticPageData

**Comment by ElectricMaxxx** [comment]
Thanks for reporting that issue. I will try to fix it.

**Comment by ElectricMaxxx** [comment]
Yea demo is working again and will hopefully never stop again. Thanks.
